name: Testing

on: push

jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Install browser dependencies
      run: npx playwright install-deps
    - name: Run tests
      run: npm test 
